# Generated by Django 4.2 on 2024-12-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_images',
            new_name='profile_image',
        ),
    ]
